version: '3.8'

services:
  app:
    container_name: express_app
    build: .
    expose:
      - "3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_JWT=${SECRET_JWT}
      - PASS_ADMIN=${PASS_ADMIN}
      - PORT=3000
    networks:
      - be_app_management_network

  db:
    image: postgres:17.2
    container_name: postgresrbac
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresrbac:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - be_app_management_network

  nginx:
    image: nginx:1.27.3-alpine-slim
    container_name: nginx_proxy
    ports:
      - "3000:80"  # Akses aplikasi di http://localhost:3000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - be_app_management_network

volumes:
  postgresrbac:

networks:
  be_app_management_network:
    driver: bridge
